### ISSUE TITLE
How to get the image after correspondence?

### ISSUE THREAD

**Issue by sareyu0753** [juhongm999/hpf#1]
As is shown in figure5 in the paper, i want to know how to test its correspondence with my own image.I want to get the image after correspondence, it's really important for me. Do you have some code about it, or some tips. Thank you sincerely.

**Comment by juhongm999** [comment]
Once you obtained keypoint correspondences for a given pair, you can find TPS transformation parameters. Send me an email if you need the code for this.

**Comment by juhongm999** [comment]
@sareyu0753 I sent you the code. 
We will add this visualization feature in our code as soon as possible.
